### ISSUE TITLE
Failed to load the go-config package

### ISSUE THREAD

**Issue by kn9ts** [joefitzgerald/go-config#2]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.3
**System**: Mac OS X 10.11.1
**Thrown From**: [go-config](https://github.com/joefitzgerald/go-config) package, v0.2.4

### Stack Trace

Failed to load the go-config package

```
At Cannot find module 'fs-plus'

Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jheneknights/.atom/packages/go-config/lib/executor.js:4:40)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jheneknights/.atom/packages/go-config/lib/main.js:4:33)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-terminal-panel",
      "wrap-guide",
      "language-perl",
      "metrics"
    ],
    "themes": [
      "one-dark-ui",
      "sepia-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, vundefined
atom-jade, v0.3.0
color-picker, v2.0.13
editorconfig, v1.2.2
file-icons, v1.6.11
go-config, v0.2.4
go-plus, v3.5.2
go-runtime, v0.2.0
jsformat, v0.9.0
jshint, v1.8.3
language-docker, v1.1.3
language-protobuf, v0.5.0
language-swig, v0.1.4
linter, v1.11.2
linter-golinter, v1.0.0
markdown-format, v2.5.1
minimap, v4.16.0
pigments, v0.19.0
pretty-json, v0.4.1
sepia-syntax, v1.0.5
terminal-panel, v1.14.1
terminal-plus, v0.14.4
wakatime, v5.0.0

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment]
Please try updating your package. It looks like you had a network error when you installed go-config. If you continue to have issues, please uninstall and reinstall the package.
