### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/atom:'

### ISSUE THREAD

**Issue by adamfisk** [joefitzgerald/go-config#23]
1. Really just saved an edited file after updating to the latest version of the plugin.

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: [go-config](https://github.com/joefitzgerald/go-config) package, v1.1.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/atom:'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:896

Error: ENOENT: no such file or directory, lstat '/atom:'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at Object.realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:262:29)
    at Executor.execSync (/Users/afisk/.atom/packages/go-config/lib/executor.js:37:24)
    at Formatter.format (/Users/afisk/.atom/packages/gofmt/lib/formatter.js:289:29)
    at /Users/afisk/.atom/packages/gofmt/lib/formatter.js:99:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1051:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1043:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:629:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:613:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:596:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:673:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:205:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:20.3.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  2x -2:18.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -2:12.3.0 core:copy (atom-text-editor.editor.is-focused)
     -1:00.7.0 core:paste (atom-text-editor.editor.is-focused)
     -0:52.7.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:47.2.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:44.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:40.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-go, v1.0.4
environment, v1.1.1
go-config, v1.1.2
go-get, v1.0.1
go-plus, v4.0.1
gofmt, v1.0.3
gometalinter-linter, v1.0.3
gorename, v1.0.0
linter, v1.11.3
navigator-godef, v1.0.2
tester-go, v1.0.1

# Dev
No dev packages
```

**Comment by Jhors2** [comment]
+1

**Comment by joefitzgerald** [comment]
What is the contents of your PATH? Could you type `⌘-option-i`, go to the "console" tab, type `process.env.PATH`, and copy the resulting text into the issue?

**Comment by jmrobison** [comment]
Uncaught TypeError: Cannot read property 'PATH' of undefined
    at <anonymous>:2:12
    at Object.InjectedScript._evaluateOn (<anonymous>:904:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:837:34)
    at Object.InjectedScript.evaluate (<anonymous>:693:21)

**Comment by jmrobison** [comment]
I added your package and did NOT restart Atom.

**Comment by jmrobison** [comment]
Running in a git environment, where git may be modifying files out from under me.

**Comment by joefitzgerald** [comment]
Is anyone open to doing a screensharing session? I would love to see this with my own eyes, as I have been unable to replicate the issue. If so, head over to #go-plus on either Slack team, and DM me your email address.

[![Slack](https://img.shields.io/badge/atom_slack-%23go--plus-blue.svg?style=flat)](https://atom-slack.herokuapp.com) [![Slack](https://img.shields.io/badge/gophers_slack-%23go--plus-blue.svg?style=flat)](https://gophersinvite.herokuapp.com)

**Comment by joefitzgerald** [comment]
OK, with the help of @jmrobison we've identified root cause. The issue occurs when you have `atom://config` added as a project folder. `atom://config` is better known as the settings dialog; and this occurs when you open the settings dialog via the `Atom > Preferences` link and then close Atom; Atom will then open up with a `config` project folder.

`gofmt` is caching the location of `gofmt` for each project folder, and obviously `atom://config` is not a valid path. A fix is forthcoming.
