### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Volumes/Home Directory/tilab'

### ISSUE THREAD

**Issue by gisiman** [joefitzgerald/go-config#29]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.4
**Thrown From**: [go-config](https://github.com/joefitzgerald/go-config) package, v1.1.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Volumes/Home Directory/tilab'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:896

Error: ENOENT: no such file or directory, lstat '/Volumes/Home Directory/tilab'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at Object.realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:262:29)
    at Executor.execSync (/Users/gisiman/.atom/packages/go-config/lib/executor.js:37:24)
    at Formatter.format (/Users/gisiman/.atom/packages/gofmt/lib/formatter.js:298:29)
    at /Users/gisiman/.atom/packages/gofmt/lib/formatter.js:99:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1051:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1043:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:629:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:613:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:596:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:673:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:205:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -5:28.3.0 core:save (atom-text-editor.editor.is-focused)
     -1:30.7.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -1:29.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:25.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:24.6.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -1:23.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:06.2.0 core:copy (atom-text-editor.editor.is-focused)
     -1:05.9.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -1:05.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:05.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -0:07.8.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -0:05.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "AtomicChar"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.4.6
atom-material-ui, v1.2.10
autocomplete-corona, v1.0.2
autocomplete-go, v1.0.6
builder-go, v1.0.0
environment, v1.2.0
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.5
gometalinter-linter, v1.1.0
gorename, v1.0.2
language-lua, v0.9.4
linter, v1.11.4
navigator-godef, v1.0.2
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment]
Is this a remote volume, mounted locally but accessed over the network?

**Comment by joefitzgerald** [comment]
Closing this due to no response.
