### ISSUE TITLE
Failed to activate the go-config package

### ISSUE THREAD

**Issue by deepch** [joefitzgerald/go-config#32]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.1
**System**: Mac OS X 10.11.4
**Thrown From**: [go-config](https://github.com/joefitzgerald/go-config) package, v1.1.4

### Stack Trace

Failed to activate the go-config package

```
At Cannot find module 'fs-plus'

Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Users/deepweb/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Users/deepweb/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/deepweb/.atom/packages/go-config/lib/executor.js:4:40)
    at Module._compile (/Users/deepweb/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/deepweb/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/deepweb/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/deepweb/.atom/packages/go-config/lib/main.js:4:42)
    at Module._compile (/Users/deepweb/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/deepweb/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/deepweb/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Users/deepweb/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/Users/deepweb/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Users/deepweb/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Users/deepweb/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Users/deepweb/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Users/deepweb/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Users/deepweb/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Users/deepweb/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Users/deepweb/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Users/deepweb/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Users/deepweb/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "term2",
      "go-rename",
      "linter-golinter",
      "go-oracle",
      "go-playground"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.20
atom-minify, v0.7.1
autocomplete-go, v1.0.6
autocomplete-php, v0.3.7
autocomplete-python, v1.7.2
builder-go, v1.0.0
color-picker, v2.1.1
environment, v1.2.0
file-icons, v1.7.2
go-config, v1.1.4
go-find-references, v1.2.3
go-get, v1.0.3
go-plus, v4.1.0
go-runtime, v0.2.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
highlight-line, v0.11.1
highlight-selected, v0.11.2
linter, v1.11.4
linter-csslint, v1.3.2
linter-jscs, v3.5.0
linter-php, v1.2.0
linter-tidy, v2.1.0
minimap, v4.21.0
navigator-godef, v1.0.2
open-recent, v5.0.0
pigments, v0.26.0
project-manager, v2.9.7
remote-edit, v1.8.24
status-bar-clock, v2.0.4
terminal-plus, v0.14.5
tester-go, v1.0.4
tool-bar, v0.4.0
tool-bar-main, v0.0.9

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment]
Please uninstall and reinstall go-config. I suspect there may have been a network issue when you were installing the package.

**Comment by joefitzgerald** [comment]
Can you please let me know if the above procedure worked?

**Comment by joefitzgerald** [comment]
Closing this due to no response.

**Comment by 0mkara** [comment]
I am getting same error. Uninstalled and reinstalled several times but can not get it working.

**Comment by alagopus** [comment]
New message: `Cannot find module 'atom-package-deps'`

This may be a separate issue under the same heading. Not sure if it is warranted to open a new issue report here.

Stack trace:
```
Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.activate (/home/********/.atom/packages/go-config/lib/main.js:17:7)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:181:20)
    at /usr/share/atom/resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:526:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:507:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:502:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:485:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:41:9)
```

**Comment by joefitzgerald** [comment]
Please update your version of Atom to the latest version. You're running a version < `1.7`.

**Comment by joefitzgerald** [comment]
I've released `v1.2.1` which calls out the need to update your version of Atom. This also removed code which depended on `atom-package-deps`, which was removed in `v1.2.0`.

**Comment by alagopus** [comment]
You were correct, and updating helped. Thank you very much!

**Comment by 0mkara** [comment]
Updating atom fixed it. Thanks.
