### ISSUE TITLE
Uncaught RangeError: Invalid string length

### ISSUE THREAD

**Issue by szabba** [joefitzgerald/go-config#37]
[Enter steps to reproduce below:]

1. Open atom.
2. ...

**Atom Version**: 1.7.3
**System**: "Arch Linux"
**Thrown From**: [go-config](https://github.com/joefitzgerald/go-config) package, v1.1.4

### Stack Trace

Uncaught RangeError: Invalid string length

```
At /home/karol/.atom/packages/go-config/lib/executor.js:101

RangeError: Invalid string length
    at stderrFn (/home/karol/.atom/packages/go-config/lib/executor.js:101:19)
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:87:13)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

### Commands

```
     -0:41.9.0 core:move-down (atom-text-editor.editor.hidden-line-numbers.is-focused)
     -0:40.5.0 pane:show-previous-item (atom-text-editor.editor.hidden-line-numbers.is-focused)
 81x -0:39.2.0 core:move-down (atom-text-editor.editor.hidden-line-numbers.is-focused)
  5x -0:24.9.0 core:move-up (atom-text-editor.editor.hidden-line-numbers.is-focused)
  3x -0:20.2.0 core:move-down (atom-text-editor.editor.hidden-line-numbers.is-focused)
     -0:17.9.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.hidden-line-numbers.is-focused)
     -0:17 core:save (atom-text-editor.editor.hidden-line-numbers.is-focused)
  5x -0:15.8.0 core:move-down (atom-text-editor.editor.hidden-line-numbers.is-focused)
  7x -0:13.8.0 core:move-up (atom-text-editor.editor.hidden-line-numbers.is-focused)
     -0:08.7.0 editor:newline (atom-text-editor.editor.hidden-line-numbers.is-focused)
  2x -0:07.8.0 core:backspace (atom-text-editor.editor.hidden-line-numbers.is-focused)
     -0:06.8.0 core:save (atom-text-editor.editor.hidden-line-numbers.is-focused)
 10x -0:05.3.0 core:move-down (atom-text-editor.editor.hidden-line-numbers.is-focused)
  3x -0:03.8.0 core:move-up (atom-text-editor.editor.hidden-line-numbers.is-focused)
     -0:02.7.0 core:move-down (atom-text-editor.editor.hidden-line-numbers.is-focused)
     -0:02.3.0 core:move-up (atom-text-editor.editor.hidden-line-numbers.is-focused)
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false,
    "closeEmptyWindows": false,
    "destroyEmptyPanes": true,
    "disabledPackages": [
      "vim-mode",
      "keybinding-resolver",
      "ionide-fsi",
      "wrap-guide",
      "local-settings",
      "linter-jslint",
      "spell-check",
      "TODOs",
      "todo-list",
      "markdown-preview-plus",
      "markdown-folder",
      "markdown-toc",
      "builder-go"
    ],
    "excludeVcsIgnoredPaths": false,
    "ignoredNames": [
      ".git",
      ".hg",
      ".cvn",
      ".DS_Store",
      "._*",
      "Thumbds.db",
      "*.pyc",
      "*.pyo"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "/home/karol/src/",
    "themes": [
      "one-dark-ui",
      "no-syntax-highlighting-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Parinfer, v1.14.0
atom-slime, v2.3.3
atom-ternjs, v0.14.1
autoclose-html, v0.23.0
autocomplete-glsl, v0.2.3
autocomplete-go, v1.0.8
autocomplete-love, v0.3.0
autocomplete-python, v1.7.2
bottom-dock, v0.4.4
bug-report, v0.7.1
django-templates, v0.5.0
environment, v1.2.0
file-icons, v1.7.8
file-watcher, v0.4.0
fold-functions, v0.4.3
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
godoc, v0.2.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
hyperclick, v0.0.36
hyperclick-love, v0.3.0
language-docker, v1.1.6
language-elm, v1.3.3
language-glsl, v2.0.1
language-haskell, v1.7.13
language-idris, v0.4.4
language-latex, v0.6.1
language-lisp, v0.2.0
language-lua, v0.9.4
language-python-django-templates, v0.1.0
language-restructuredtext, v0.13.0
language-rust, v0.4.6
language-scala, v1.1.6
language-scheme, v1.4.0
linter, v1.11.4
linter-clojure, v1.1.2
linter-elm-make, v0.4.0
linter-flake8, v1.13.0
linter-luaparse, v0.2.0
linter-scalac, v1.4.0
markdown-scroll-sync, v2.1.2
merge-conflicts, v1.4.2
navigator-godef, v1.0.3
no-syntax-highlighting-syntax, v0.2.11
project-manager, v2.9.7
python-isort, v0.0.7
python-tools, v0.6.7
scala-format, v0.1.8
select-rectangle, v1.0.2
term3, v0.22.0
tester-go, v1.0.4
todo-manager, v0.2.8
toggle-gutter, v0.2.2
wordcount, v2.6.0

# Dev
No dev packages
```

**Comment by szabba** [comment]
It happened only once. It should be fine to disregard it.

**Comment by jfesler** [comment]
Happening to me.

```
/Users/jfesler/.atom/packages/go-config/lib/executor.js:101
Hide Stack Trace
RangeError: Invalid string length
    at stderrFn (/Users/jfesler/.atom/packages/go-config/lib/executor.js:101:19)
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:87:13)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:531:20)
```

**Comment by jfesler** [comment]
Atom 1.10.0 Mac
go-config 1.2.1

Upgrading now to 1.2.3
